export const placesData = [
    {
        name: "Breakfast Republic",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Pancakes, Waffles",
        city: "San Diego",
        state: "California",
        founded: "2013",
    },
    {
        name: "iHop",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Steak, Ham",
        city: "Chula Vista",
        state: "California",
        founded: "2013",
    },
    {
        name: "Denny's",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Eggs, Pancakes, Waffles",
        city: "Otay Mesa",
        state: "California",
        founded: "2021",
    },
    {
        name: "Breakfast Republic",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Pancakes, Waffles",
        city: "San Diego",
        state: "California",
        founded: "2013",
    },
    {
        name: "iHop",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Steak, Ham",
        city: "Chula Vista",
        state: "California",
        founded: "2013",
    },
    {
        name: "Denny's",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Eggs, Pancakes, Waffles",
        city: "Otay Mesa",
        state: "California",
        founded: "2021",
    },
    {
        name: "Breakfast Republic",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Pancakes, Waffles",
        city: "San Diego",
        state: "California",
        founded: "2013",
    },
    {
        name: "iHop",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Steak, Ham",
        city: "Chula Vista",
        state: "California",
        founded: "2013",
    },
    {
        name: "Denny's",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Eggs, Pancakes, Waffles",
        city: "Otay Mesa",
        state: "California",
        founded: "2021",
    },
    {
        name: "Breakfast Republic",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Pancakes, Waffles",
        city: "San Diego",
        state: "California",
        founded: "2013",
    },
    {
        name: "iHop",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Steak, Ham",
        city: "Chula Vista",
        state: "California",
        founded: "2013",
    },
    {
        name: "Denny's",
        pic: "https://dummyimage.com/600x400/000/fff.jpg&text=placeholder",
        cuisines: "Eggs, Pancakes, Waffles",
        city: "Otay Mesa",
        state: "California",
        founded: "2021",
    },
];
