export const placesData = [
    {
        name: "Breakfast Republic",
        pic: "https://img.sunset02.com/sites/default/files/styles/medium_2x/public/image/2015/11/main/socal-insider-san-diego-breakfast-republic-benedict-1215-xl.jpg",
        cuisines: "Pancakes, Waffles",
        city: "San Diego",
        state: "California",
        founded: "2013",
    },
    {
        name: "iHop",
        pic: "https://www.fsrmagazine.com/sites/default/files/styles/homepage_carousel_2x_640x476/public/2021-04/IHOP.jpg?itok=PWQZU-Z9",
        cuisines: "Steak, Ham",
        city: "Chula Vista",
        state: "California",
        founded: "2013",
    },
    {
        name: "Denny's",
        pic: "https://i.insider.com/5a57b30925954cc20e8b4db5?width=838&format=jpeg",
        cuisines: "Eggs, Pancakes, Waffles",
        city: "Otay Mesa",
        state: "California",
        founded: "2021",
    },
    {
        name: "Frutas 100%",
        pic: "https://popmenucloud.com/kipurowm/0c10b5ed-9901-421c-bcc8-25801db9da08",
        cuisines: "Pancakes, Waffles",
        city: "San Diego",
        state: "California",
        founded: "2013",
    },
    {
        name: "Italgo Pasta Bar",
        pic: "https://www.thestarnews.com/wp-content/uploads/2017/12/web.Itaslgo-21.jpg",
        cuisines: "Steak, Ham",
        city: "Chula Vista",
        state: "California",
        founded: "2013",
    },
    {
        name: "BJ's Restaurant & Brewhouse",
        pic: "https://resizer.otstatic.com/v2/photos/wide-huge/1/25319557.jpg",
        cuisines: "Eggs, Pancakes, Waffles",
        city: "Otay Mesa",
        state: "California",
        founded: "2021",
    },
    {
        name: "Galley At the Marina",
        pic: "http://thegalleyatthemarina.com/wp-content/uploads/2021/01/Maryland-Crab-Cakes-Appetizers-Galley-at-the-Marina.jpg",
        cuisines: "Pancakes, Waffles",
        city: "San Diego",
        state: "California",
        founded: "2013",
    },
    {
        name: "Olive Garden",
        pic: "https://media.olivegarden.com/images/site/ext/pages/_promotions/delivery/delivery-hhd-03-062518.jpg",
        cuisines: "Steak, Ham",
        city: "Chula Vista",
        state: "California",
        founded: "2013",
    },
    {
        name: "Buffalo Wild Wings",
        pic: "https://media-cdn.tripadvisor.com/media/photo-s/17/4e/20/af/photo1jpg.jpg",
        cuisines: "Eggs, Pancakes, Waffles",
        city: "Otay Mesa",
        state: "California",
        founded: "2021",
    },
    {
        name: "Hector's Mariscos",
        pic: "https://media-cdn.tripadvisor.com/media/photo-s/06/da/f9/ba/hector-s-maricos.jpg",
        cuisines: "Pancakes, Waffles",
        city: "San Diego",
        state: "California",
        founded: "2013",
    },
    {
        name: "Tacos El Gordo",
        pic: "https://cdn.vox-cdn.com/thumbor/Hl920QCKlp6xBxUMclQspJ7G9A4=/0x0:1000x562/1200x800/filters:focal(420x201:580x361)/cdn.vox-cdn.com/uploads/chorus_image/image/54756563/tacos_el_gordo.0.jpg",
        cuisines: "Steak, Ham",
        city: "Chula Vista",
        state: "California",
        founded: "2013",
    },
    {
        name: "Applebee's",
        pic: "https://media-cdn.tripadvisor.com/media/photo-s/0f/43/21/05/photo2jpg.jpg",
        cuisines: "Eggs, Pancakes, Waffles",
        city: "Otay Mesa",
        state: "California",
        founded: "2021",
    },
];
